### ISSUE TITLE
Test failures with Twisted 25.5.0

### ISSUE THREAD

**Issue by arkamar** [element-hq/synapse#18565]
### Description

Synapse's testsuite fails with Twisted 25.5.0. I bisected the root cause to commit https://github.com/twisted/twisted/commit/e8090c4e0709deb931f533fe095cc50ebca3422e. However, the current form of the failures starts appearing with commit https://github.com/twisted/twisted/commit/2dc339a76e9def0caa2f0a6ba1488ab4d872daa2.

[error.log](https://github.com/user-attachments/files/20790379/error.log)

### Steps to reproduce

- Install Twisted 25.5.0
- run tests
- observe failures

### Homeserver

homeserver

### Synapse Version

1.131.0

### Installation Method

Other (please mention below)

### Database

sqlite

### Workers

Single process

### Platform

Gentoo

### Relevant log output

```shell
[snip ...]

tests.test_server.JsonResourceTests.test_no_handler
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/var/tmp/portage/net-im/synapse-1.131.0/work/synapse-1.131.0/tests/test_server.py", line 331, in test_good_response
    channel = make_request(
  File "/var/tmp/portage/net-im/synapse-1.131.0/work/synapse-1.131.0/tests/server.py", line 432, in make_request
    req = request(channel, site)
  File "/var/tmp/portage/net-im/synapse-1.131.0/work/synapse-1.131.0-python3_13/install/usr/lib/python3.13/site-packages/synapse/http/site.py", line 91, in __init__
    super().__init__(channel, *args, **kw)
  File "/usr/lib/python3.13/site-packages/twisted/web/server.py", line 107, in __init__
    parsePOSTFormSubmissionBool = channel.site._parsePOSTFormSubmission
builtins.AttributeError: 'FakeSite' object has no attribute '_parsePOSTFormSubmission'

tests.test_server.WrapHtmlRequestHandlerTests.test_good_response
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/var/tmp/portage/net-im/synapse-1.131.0/work/synapse-1.131.0/tests/test_server.py", line 394, in test_head_request
    channel = make_request(
  File "/var/tmp/portage/net-im/synapse-1.131.0/work/synapse-1.131.0/tests/server.py", line 432, in make_request
    req = request(channel, site)
  File "/var/tmp/portage/net-im/synapse-1.131.0/work/synapse-1.131.0-python3_13/install/usr/lib/python3.13/site-packages/synapse/http/site.py", line 91, in __init__
    super().__init__(channel, *args, **kw)
  File "/usr/lib/python3.13/site-packages/twisted/web/server.py", line 107, in __init__
    parsePOSTFormSubmissionBool = channel.site._parsePOSTFormSubmission
builtins.AttributeError: 'FakeSite' object has no attribute '_parsePOSTFormSubmission'

tests.test_server.WrapHtmlRequestHandlerTests.test_head_request
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/var/tmp/portage/net-im/synapse-1.131.0/work/synapse-1.131.0/tests/test_server.py", line 351, in test_redirect_exception
    channel = make_request(
  File "/var/tmp/portage/net-im/synapse-1.131.0/work/synapse-1.131.0/tests/server.py", line 432, in make_request
    req = request(channel, site)
  File "/var/tmp/portage/net-im/synapse-1.131.0/work/synapse-1.131.0-python3_13/install/usr/lib/python3.13/site-packages/synapse/http/site.py", line 91, in __init__
    super().__init__(channel, *args, **kw)
  File "/usr/lib/python3.13/site-packages/twisted/web/server.py", line 107, in __init__
    parsePOSTFormSubmissionBool = channel.site._parsePOSTFormSubmission
builtins.AttributeError: 'FakeSite' object has no attribute '_parsePOSTFormSubmission'

tests.test_server.WrapHtmlRequestHandlerTests.test_redirect_exception
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/var/tmp/portage/net-im/synapse-1.131.0/work/synapse-1.131.0/tests/test_server.py", line 373, in test_redirect_exception_with_cookie
    channel = make_request(
  File "/var/tmp/portage/net-im/synapse-1.131.0/work/synapse-1.131.0/tests/server.py", line 432, in make_request
    req = request(channel, site)
  File "/var/tmp/portage/net-im/synapse-1.131.0/work/synapse-1.131.0-python3_13/install/usr/lib/python3.13/site-packages/synapse/http/site.py", line 91, in __init__
    super().__init__(channel, *args, **kw)
  File "/usr/lib/python3.13/site-packages/twisted/web/server.py", line 107, in __init__
    parsePOSTFormSubmissionBool = channel.site._parsePOSTFormSubmission
builtins.AttributeError: 'FakeSite' object has no attribute '_parsePOSTFormSubmission'

tests.test_server.WrapHtmlRequestHandlerTests.test_redirect_exception_with_cookie
-------------------------------------------------------------------------------
Ran 4074 tests in 176.816s

FAILED (skips=309, failures=64, errors=38, successes=3664)
```

### Anything else that would be useful to know?

Gentoo package works fine with Twisted 24.11.0, but we are skipping `test_recovery` test with this patch https://github.com/gentoo/gentoo/blob/dee8d327eeb6621e93cbab54bb73b141912c05d1/net-im/synapse/files/synapse-1.123.0-skip-recovery-test.patch.

**Comment by anoadragon453** [comment]
Seems the main cause is that https://github.com/twisted/twisted/pull/12413/files#diff-6c8252af78a4a1c3cdfd2474b7349fb479c0e0a308a8336e4ddab729f55df9baR802 added a `_parsePOSTFormSubmission` attribute to `twisted.web.server.Site` which our `FakeSite` implementation for testing lacks:

https://github.com/element-hq/synapse/blob/73a38384f51d5ac3df81a93c0f92b23e649d742f/tests/server.py#L332-L356

**Comment by anoadragon453** [comment]
https://github.com/element-hq/synapse/pull/18577 should fix the issue.

**Comment by arkamar** [comment]
The #18577 fixed 24 errors but it didn't solved the issue completely for me in 1.131.0:
```diff
-FAILED (skips=309, failures=64, errors=38, successes=3664)
+FAILED (skips=309, failures=64, errors=14, successes=3688)
```
similarly in 1.132.0:
```diff
-FAILED (skips=309, failures=64, errors=38, successes=3696)
+FAILED (skips=309, failures=64, errors=14, successes=3720)
```

**Comment by anoadragon453** [comment]
@arkamar thanks for reporting. I'm working on fixing the rest of the issues (including mypy failures).

**Comment by anoadragon453** [comment]
@arkamar I've updated #18577. Please give it another try.

**Comment by arkamar** [comment]
Yes, it works now!
```
PASSED (skips=309, successes=3797)
```
Thanks!

I run tests with Twisted 24.11.0 and 25.5.0, it passed tests in both cases.
