### PR TITLE
Fix bug with creating public rooms on workers

### PR DESCRIPTION
**Pull request by erikjohnston**
If room publication is disabled then creating public rooms on workers would not work.

Introduced in #16811.

Stack trace:

```
AttributeError: 'GenericWorkerStore' object has no attribute 'set_room_is_public'
  File "synapse/http/server.py", line 332, in _async_render_wrapper
    callback_return = await self._async_render(request)
  File "synapse/http/server.py", line 544, in _async_render
    callback_return = await raw_callback_return
  File "synapse/rest/client/room.py", line 171, in on_POST
    return await self._do(request, requester)
  File "synapse/rest/client/room.py", line 176, in _do
    room_id, _, _ = await self._room_creation_handler.create_room(
  File "synapse/handlers/room.py", line 921, in create_room
    await self.store.set_room_is_public(room_id, False)
```

### CODE REVIEW

**Review by anoadragon453 — APPROVED** [review]
Assuming that
